import type { Metadata } from "next";
import {  Montserrat,  } from "next/font/google";
import "./globals.css";


const poppins = Montserrat({
  weight: ["400", "700", "900", "800", "600", "500"],
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Travel and Stay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
